### ISSUE TITLE
I really like this stuff.

### ISSUE THREAD

**Issue by GerryG** [cliftonm/HOPE#3]
I'm an early Open Money/Metacurrency person who is getting caught up again. Noticed this project on the demo and wanted to learn more.

I'm really interested in getting in touch with you, I just followed you on github, just let me know what channels are best for you.

Except the choice of C# ;) I really liked the results though, I hope there are other platforms that can do this well.

**Comment by cliftonm** [comment]
Hi Gerry,

It would be great to connect.  Email me directly at marc.clifton@gmail.com and I'll provide you with some additional "channels of communication."  As to other platforms, I've been really wanting to see an implementation of this in a way that supports creating "web app receptors", so I'm open to a lot of other options!
